ARM macOS build and other improvements (#195)
* ARM macOS build

* nothing is sacred anymore

* i forgor how to python

* Remove macOS .zip artifacts

* """"""Fix"""""" types and formatting

* Remove wrapper script in Intel version

diff --git a/.github/workflows/build-test-publish.yml b/.github/workflows/build-test-publish.yml
--- a/.github/workflows/build-test-publish.yml
+++ b/.github/workflows/build-test-publish.yml
@@ -101,6 +101,7 @@ jobs:
       - build
       - package-windows
       - package-mac
+      - package-mac-arm64
     runs-on: ubuntu-latest
     name: Deploy wheels to PyPI
     steps:
@@ -297,16 +298,6 @@ jobs:
           # Package
           ./build-mac.sh $PACKAGE_VERSION
 
-          # Creating a zip makes the artifact upload much faster since there are so many files
-          zip -r skytemple-randomizer-mac.zip "dist/SkyTemple Randomizer.app" > /dev/null
-
-      - name: Upload .app
-        uses: actions/upload-artifact@v4
-        with:
-          name: skytemple-randomizer-mac-app-x86_64
-          path: |
-            installer/skytemple-randomizer-mac.zip
-
       - name: Create installer
         run: |
           # See https://github.com/sindresorhus/create-dmg
@@ -320,5 +311,82 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: skytemple-randomizer-mac-dmg-x86_64
+          path: |
+            installer/SkyTemple Randomizer*.dmg
+
+  package-mac-arm64:
+    runs-on: macos-14
+    name: Build and package for Mac OS (ARM)
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Rewrite version for dev if not tag
+        if: "!startsWith(github.ref, 'refs/tags/')"
+        run: |
+          perl -i -pe "s/version\s*=\s*\"(.*?)(\.rc.*|\.a.*|\.post.*)?\"/version=\"\1.dev0+${GITHUB_SHA::8}\"/" pyproject.toml
+          echo "IS_DEV_BUILD=1" >> $GITHUB_ENV
+      - name: Note version
+        run: |
+          python3 -m venv .yq-venv
+          . .yq-venv/bin/activate
+          pip install yq
+          echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
+      - name: Install base packages
+        run: |
+          brew install pygobject3 gtk4 python@3.12 libadwaita adwaita-icon-theme sdl meson cmake
+          echo "PATH=/usr/local/opt/python@3.12/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
+          
+          python3.12 -m venv .venv
+          . .venv/bin/activate
+          pip3 debug --verbose  # print compatible tags etc. for debugging purposes
+
+      - name: Make sure PyGObject is available.
+        run: |
+          . .venv/bin/activate
+          pip3 install "pygobject>=3.44.0"
+      - name: Convert Blueprint files
+        run: |
+          . .venv/bin/activate
+          ./build-blp-to-ui.sh
+      - name: Install and package
+        run: |
+          . .venv/bin/activate
+          # Install other dependencies and SkyTemple Randomizer itself
+          pip3 install skytemple-rust 'pyinstaller~=6.0'
+          pip3 install -r requirements-mac-windows.txt
+          # Generate MO localization files
+          installer/generate-mo.sh
+          pip3 install '.[gtk]'
+          if [ -n "$IS_DEV_BUILD" ]; then
+            installer/install-skytemple-components-from-git.sh
+          fi
+          
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "4.0"); gi.require_version("Adw", "1"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk, Adw'
+
+          cd installer
+
+          # Download armips
+          curl https://skytemple.org/build_deps/mac/armips-mac-arm64 -o armips
+          chmod +x armips
+
+          # Package
+          ./build-mac.sh $PACKAGE_VERSION
+
+      - name: Create installer
+        run: |
+          # See https://github.com/sindresorhus/create-dmg
+          # create-dmg automatically generates an installer icon if imagemagick is installed
+          brew install graphicsmagick imagemagick
+
+          # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
+          npx create-dmg --dmg-title="SkyTemple Randomizer" "installer/dist/SkyTemple Randomizer.app" installer || true
+
+      - name: Upload .dmg
+        uses: actions/upload-artifact@v4
+        with:
+          name: skytemple-randomizer-mac-dmg-arm64
           path: |
             installer/SkyTemple Randomizer*.dmg
